Inital commit for file management page
alliance-genome/agr_literature_ui pull request #59
Opened 2023-04-13 16:44 UTC by pjhale

Will need merge to main since the db has changed and api calls are  failing.

2023-04-28 20:28 UTC, azurebrd commented on src/components/Tracker.js
> +function getOktaModAccess(oktaGroups) {
This should probably just import the other module that exists, so we don't have to maintain 2 copies when things change ?  We're probably going to be changing something for okta Tester group, which would override access with whatever they set manually through the UI.

2023-04-28 20:31 UTC, azurebrd requested changes
Looks great @pjhale .  Just the request to import the existing getOktaModAccess if they're meant to do the same thing.  But if you think it's better to have a separate one because it's a different use-case, we can talk with Valerio when he's back.  Thanks !

2023-05-01 19:18 UTC, azurebrd approved these changes
@pjhale explained that we need to _not_ have developer, so can't use the other function.  @valearna agrees it's fine to have separate functions for now until we can add some Person-based API thing or a Tester mod changer function in that story.

2023-05-03 18:23 UTC, valearna approved these changes

2023-05-03 18:25 UTC, merged